"use strict";

(() => {
  const GROUPS = {
    core: {
      name: "Core",
      label: "Core fundamentals",
      description: "Safety, environmental impact, refrigerant handling, recovery terminology, and Section 608 fundamentals.",
      scenes: [["Site", "Confirm the work order and responsibility."], ["Equipment", "Identify the appliance and refrigerant."], ["Service area", "Inspect conditions and make a compliant plan."], ["Service van", "Select approved tools, PPE, and cylinders."]],
      tasks: ["Confirm the service request", "Identify refrigerant and appliance", "Establish safe conditions", "Inspect the service situation", "Select a compliant procedure", "Submit the decision", "Complete and document the work"]
    },
    type1: {
      name: "Type I",
      label: "Type I · Small appliances",
      description: "Factory-charged, hermetically sealed appliances containing five pounds or less of refrigerant.",
      scenes: [["Customer", "Confirm the symptom and appliance history."], ["Appliance", "Inspect the sealed system and controls."], ["Recovery station", "Recover, repair, and verify the appliance."], ["Service van", "Select small-appliance recovery tools."]],
      tasks: ["Confirm the complaint", "Identify the appliance", "Establish safe conditions", "Inspect the sealed system", "Meet the recovery requirement", "Submit a diagnosis", "Repair and document"]
    },
    type2: {
      name: "Type II",
      label: "Type II · High-pressure",
      description: "High- and very-high-pressure stationary appliances other than small appliances and MVACs.",
      scenes: [["Operator", "Confirm the complaint and operating history."], ["Indoor section", "Check load, airflow, and heat transfer."], ["Mechanical area", "Measure the refrigeration circuit and locate the fault."], ["Service van", "Select recovery and diagnostic equipment."]],
      tasks: ["Confirm the complaint", "Identify the system", "Rule out load and airflow", "Verify electrical operation", "Evaluate the refrigerant circuit", "Submit a diagnosis", "Repair and recommission"]
    },
    type3: {
      name: "Type III",
      label: "Type III · Low-pressure",
      description: "Low-pressure chillers, vacuum-side leak behavior, purge systems, recovery, and water-side concerns.",
      scenes: [["Plant operator", "Review chiller logs and the reported symptom."], ["Chiller", "Inspect the evaporator, condenser, and safety devices."], ["Machine room", "Test, recover, repair, and verify the low-pressure system."], ["Recovery station", "Prepare the correct recovery equipment and cylinders."]],
      tasks: ["Review the operating history", "Identify the chiller", "Establish safe conditions", "Evaluate purge and water systems", "Complete low-pressure testing", "Submit a diagnosis", "Repair and recommission"]
    }
  };

  const FOCUS = {
    core: [
      { name:"Venting decision", visual:"The service requires opening a sealed refrigerant circuit; no isolation valve protects the affected section.", operating:"The refrigerant is not listed as exempt for this end use, and the planned opening would release charge.", confirm:"The recovery machine is certified for the appliance category and the receiving cylinder is approved and in date.", diagnosis:"Recover the refrigerant before opening the circuit; intentional venting is prohibited.", distractors:["Release only vapor because liquid is the regulated phase","Dilute the refrigerant with nitrogen and vent the mixture","Open the system briefly because a service call is automatically de minimis"], repair:"Identify the refrigerant, recover with certified equipment, perform the work, leak-check, evacuate, and document the final charge.", repairDistractors:["Vent until pressure reaches zero and begin the repair","Use oxygen to push the remaining refrigerant out","Recover only enough refrigerant to stop liquid flow"], explanation:"A good-faith recovery process may create small unavoidable releases, but a planned release is not made acceptable by calling it de minimis." },
      { name:"Recovery cylinder safety", visual:"The recovery cylinder has legible markings and no visible damage, but its gross weight is approaching the allowed fill limit.", operating:"Scale readings show there is not enough remaining cylinder capacity for the estimated system charge.", confirm:"A second compatible recovery cylinder is available and has current qualification markings.", diagnosis:"Stop and change to a suitable cylinder before recovery; never overfill a recovery cylinder.", distractors:["Cool the cylinder with dry ice so more refrigerant will fit","Continue until liquid reaches the cylinder valve","Vent the vapor space to make room for more liquid"], repair:"Use a scale, observe the cylinder’s rated fill limit, keep refrigerants separated, and transport the cylinder secured and labeled.", repairDistractors:["Estimate fill by cylinder temperature alone","Mix compatible refrigerants to save cylinder space","Lay the cylinder loose in the truck for transport"], explanation:"Recovery cylinder capacity and condition are safety controls, not efficiency suggestions." },
      { name:"Certification scope", visual:"The work order includes attaching gauges and adding refrigerant to stationary equipment.", operating:"The appliance category on the nameplate does not match the technician credential presented for the call.", confirm:"A technician with the correct Section 608 certification is available to take responsibility for the work.", diagnosis:"The refrigerant-side work must be performed by a technician certified for this appliance category.", distractors:["Any EPA card covers every stationary appliance","Certification is unnecessary when the owner supplies refrigerant","Only recovery-machine ownership determines who may perform the work"], repair:"Match the technician certification to the appliance category, or work as a properly supervised apprentice where allowed.", repairDistractors:["Proceed if the customer signs a waiver","Limit the work to adding refrigerant without gauges","Borrow another technician’s certification number"], explanation:"Section 608 certification types correspond to the equipment being serviced; Universal covers all types." },
      { name:"Recovered refrigerant ownership", visual:"Recovered refrigerant is clean enough for reuse, but the customer wants it transferred to an unrelated owner.", operating:"The refrigerant would change ownership rather than return to equipment owned by the same person.", confirm:"An EPA-certified reclaimer is available to process the recovered refrigerant.", diagnosis:"Refrigerant that changes ownership must be reclaimed by an EPA-certified reclaimer.", distractors:["Recycling on the service truck is always equivalent to reclamation","Any recovered refrigerant may be sold directly to another owner","Filtering through one drier makes the refrigerant legally reclaimed"], repair:"Send the refrigerant to a certified reclaimer and maintain the required transfer documentation.", repairDistractors:["Mix it into a common recovery cylinder and resell it","Return it to any system using the same refrigerant number","Vent the vapor and sell the remaining liquid"], explanation:"Recovery, recycling, and reclamation are distinct processes; ownership change triggers the reclamation requirement." },
      { name:"Blend handling", visual:"The cylinder label identifies a zeotropic or near-azeotropic blend and specifies liquid removal.", operating:"A vapor-only charging plan could change the composition of the blend through fractionation.", confirm:"A scale and throttling device are available to meter liquid safely into the system.", diagnosis:"Remove the blend from the cylinder as liquid and meter it according to the equipment procedure.", distractors:["Charge only vapor so the blend separates safely","Shake the system after charging to remix the components","Add whichever component has the highest pressure first"], repair:"Verify the exact refrigerant, charge the blend as liquid using a scale, and prevent liquid slugging at the compressor.", repairDistractors:["Charge by cylinder pressure alone","Top off with a different blend having similar pressures","Invert every recovery cylinder regardless of its valve design"], explanation:"Liquid removal preserves blend composition; the liquid must still be introduced in a controlled way." },
      { name:"Moisture and oil", visual:"Oil is discolored and the system has been open to humid air during a component replacement.", operating:"Moisture can react with oil and refrigerant, creating acids and damaging insulation and metal surfaces.", confirm:"The correct replacement oil, filter drier, deep-vacuum setup, and micron gauge are available.", diagnosis:"Control moisture with correct oil handling, a properly sized filter drier, and a verified evacuation.", distractors:["Add alcohol to absorb the moisture","Heat the compressor and vent the water vapor","Mix mineral and POE oils to improve moisture tolerance"], repair:"Minimize open time, replace the drier, use compatible oil, evacuate with a micron gauge, and verify vacuum stability.", repairDistractors:["Judge dryness by manifold pressure only","Reuse oil that was stored in an open container","Purge repeatedly with refrigerant instead of evacuating"], explanation:"Moisture and incompatible oils can cause chemical and mechanical damage that pressure readings alone will not reveal." },
      { name:"Refrigerant safety", visual:"The work area is confined and the refrigerant safety data calls for ventilation and eye and skin protection.", operating:"A release could displace oxygen; liquid contact could cause frostbite, and decomposition products may be hazardous near flame.", confirm:"Ventilation, refrigerant-rated gloves, goggles, and an appropriate monitor are available.", diagnosis:"Control exposure before connecting service equipment or moving refrigerant.", distractors:["Refrigerants are safe whenever they are nonflammable","Odor is a reliable substitute for an oxygen monitor","Natural refrigerants require no special safety controls"], repair:"Ventilate, use the SDS and required PPE, eliminate ignition or decomposition hazards, and follow the refrigerant’s safety classification.", repairDistractors:["Use an open flame to locate leaks quickly","Rely on cotton gloves for liquid refrigerant","Work alone because the cylinder is small"], explanation:"Low flammability does not mean low toxicity, and natural does not mean harmless." },
      { name:"Environmental impact", visual:"Two refrigerants under consideration have different ozone-depletion and global-warming characteristics.", operating:"ODP describes ozone impact relative to a reference, while GWP compares heat trapping over a stated time horizon.", confirm:"The equipment manufacturer and current SNAP listing identify acceptable substitutes for the specific end use.", diagnosis:"Evaluate ODP, GWP, safety class, compatibility, efficiency, and end-use acceptability together.", distractors:["Choose solely by the lowest cylinder pressure","Any zero-ODP refrigerant is automatically an approved drop-in","GWP and ODP measure the same atmospheric effect"], repair:"Use an acceptable refrigerant specified for the equipment or a properly engineered retrofit; label and document the change.", repairDistractors:["Create a field blend with a similar pressure","Replace refrigerant without checking oil or components","Use any natural refrigerant because it is exempt everywhere"], explanation:"Environmental metrics, safety, equipment design, and legal acceptability are separate considerations." },
      { name:"Certified recovery equipment", visual:"One recovery machine has the required certification label; an older unmarked machine does not.", operating:"The planned service requires recovering refrigerant before the appliance is opened.", confirm:"The labeled machine is rated for the refrigerant and appliance category and its hoses are in good condition.", diagnosis:"Use recovery equipment certified for the applicable appliance and refrigerant category.", distractors:["Use the unmarked machine if it reaches the same pressure","Recover into a disposable cylinder","Use the system compressor as the only proof of compliance"], repair:"Verify the equipment label, follow the manufacturer instructions, use low-loss fittings, and recover to the required level.", repairDistractors:["Remove the equipment label after the first use","Use any vacuum pump as a recovery machine","Stop recovery when frost first appears"], explanation:"Certified recovery equipment and correct operating procedures are both required." },
      { name:"Leak and service records", visual:"A large appliance has repeated additions of refrigerant and incomplete service records.", operating:"The charge size, refrigerant type, application category, and calculated leak rate must be established before regulatory duties can be determined.", confirm:"Service dates, quantities added, full charge, leak inspections, and verification-test results can be reconstructed.", diagnosis:"Calculate and document the leak rate, then apply the current rule that covers this refrigerant and appliance.", distractors:["Leak rules are identical for every refrigerant and charge size","Adding refrigerant without records resets the leak rate","Only the equipment manufacturer may calculate a leak rate"], repair:"Repair confirmed leaks, perform required verification tests, and retain accurate service records under the applicable rule.", repairDistractors:["Top off the appliance and erase prior additions","Estimate the full charge from suction pressure","Wait for total charge loss before documenting the leak"], explanation:"Current leak obligations depend on specific facts; records are necessary to make and prove the compliance decision." }
    ],
    type1: [
      { name:"Operating-compressor recovery", visual:"The compressor starts and the sealed system has accessible process tubing.", operating:"Post-1993 recovery equipment is available and the compressor can circulate refrigerant during recovery.", confirm:"The recovery setup can meet 90 percent recovery or evacuate the appliance to four inches of mercury vacuum.", diagnosis:"Use the operating compressor and certified equipment to meet the small-appliance recovery requirement.", distractors:["Recover only 80 percent because every small appliance uses that value","Vent vapor until the compressor cycles off","Open the process tube before connecting recovery equipment"], repair:"Recover 90 percent or reach four inches Hg vacuum, complete the repair, remove temporary access hardware, evacuate, and weigh in the charge.", repairDistractors:["Stop at atmospheric pressure","Leave a piercing valve as the permanent service port","Charge until the suction line feels cool"], explanation:"With post-1993 equipment and a functional compressor, the small-appliance percentage is 90 percent; four inches Hg vacuum is an alternative endpoint." },
      { name:"Failed-compressor recovery", visual:"The compressor winding is open and the appliance cannot circulate refrigerant.", operating:"The recovery machine is post-1993, but the appliance compressor is nonfunctional.", confirm:"Access to both high and low sides will improve recovery from trapped sections.", diagnosis:"Recover at least 80 percent or reach four inches Hg vacuum with the compressor nonfunctional.", distractors:["No recovery is required when the compressor has failed","The requirement increases to 100 percent","Vent the high side and recover only the low side"], repair:"Establish effective access, recover to the required level, replace the failed component, evacuate, and charge by weight.", repairDistractors:["Heat the cylinder with a torch","Use oxygen to raise appliance pressure","Discard the appliance with charge remaining"], explanation:"A failed compressor changes the percentage requirement, not the obligation to recover." },
      { name:"System-dependent recovery", visual:"A passive recovery bag and a system-dependent device are selected for a small factory charge.", operating:"The appliance compressor and an external heat source can help move refrigerant, but liquid can remain trapped in oil and cold components.", confirm:"The recovery container is compatible and the procedure prevents pressure or temperature abuse.", diagnosis:"Use system-dependent recovery only within its allowed small-appliance application and follow the device procedure.", distractors:["A passive device is approved for every appliance size","Use compressed air to sweep refrigerant into the bag","Warm the cylinder above its rated temperature"], repair:"Connect correctly, use controlled warming where allowed, monitor recovery, and verify the required endpoint.", repairDistractors:["Puncture the recovery bag after use","Mix refrigerants because the bag is disposable","Stop as soon as pressure equalizes"], explanation:"System-dependent recovery relies on the appliance pressure or compressor and is limited to appropriate small-appliance work." },
      { name:"Temporary access valve", visual:"A saddle-type piercing valve was installed to diagnose the sealed system.", operating:"The temporary valve can leak over time and is not a reliable permanent access fitting.", confirm:"The refrigerant can be recovered and a brazed process stub or approved permanent fitting can be installed.", diagnosis:"Do not leave a piercing valve as the permanent repair.", distractors:["Tighten the piercing valve and conceal it under insulation","Add sealant around the valve body","Vent the appliance before removing the valve"], repair:"Recover refrigerant, remove the temporary valve, install an approved permanent access method, leak-test, evacuate, and recharge.", repairDistractors:["Leave two piercing valves for redundancy","Use a tire valve without brazing","Crimp the tube while it is still pressurized"], explanation:"Temporary access devices are common leak points and should be replaced with a durable sealed-system repair." },
      { name:"Appliance disposal", visual:"The appliance is tagged for scrap and still contains its factory refrigerant charge.", operating:"The final disposer needs documentation showing who recovered the refrigerant and when.", confirm:"A certified recovery device and suitable recovery cylinder are available before transport to final disposal.", diagnosis:"Recover the refrigerant and document recovery before final disposal.", distractors:["Cut the lines so the scrap yard knows the appliance is empty","The owner may vent a small factory charge","Leave recovery to the landfill without notifying it"], repair:"Recover to the required level, label the appliance as processed, and provide the required disposal record.", repairDistractors:["Use a disposable cylinder for recovered refrigerant","Mix the charge with used oil","Remove only the compressor and discard the cabinet"], explanation:"Small-appliance disposal still requires proper refrigerant recovery and documentation." },
      { name:"Restriction and moisture", visual:"Frost forms at the capillary entrance and temperature drops sharply across the filter drier.", operating:"The compressor runs, but the evaporator is starved and the sealed system was previously opened.", confirm:"The evidence supports a restriction and possible moisture contamination rather than a simple low charge.", diagnosis:"A restricted drier or capillary is starving the evaporator.", distractors:["The appliance is overcharged solely because the condenser is warm","The thermostat is satisfied","The compressor is pumping too much oil"], repair:"Recover refrigerant, replace the restricted drier, clear or replace the capillary as needed, evacuate with a micron gauge, and charge by weight.", repairDistractors:["Add refrigerant until frost disappears","Heat the drier and leave it installed","Purge moisture with refrigerant vapor"], explanation:"A localized temperature drop and starved evaporator point to a restriction; opening the system requires moisture control." },
      { name:"Blend charging", visual:"The nameplate specifies a refrigerant blend and an exact factory charge by weight.", operating:"Vapor removal from the cylinder could fractionate the blend, and the small charge makes guessing especially inaccurate.", confirm:"The correct refrigerant, scale, and a controlled liquid-metering method are available.", diagnosis:"Charge the specified blend from the cylinder as liquid and weigh the exact amount.", distractors:["Charge vapor until the compressor amperage rises","Use any blend with a similar standing pressure","Top off without repairing the leak"], repair:"Repair the leak, evacuate, remove blend from the cylinder as liquid, meter it safely, and verify operation.", repairDistractors:["Mix two pure refrigerants in the appliance","Charge by frost pattern only","Use the recovery cylinder as the charging cylinder without identifying contents"], explanation:"Factory charges are sensitive to composition and mass; use the specified blend and a scale." },
      { name:"Sealed-system leak", visual:"Oil staining and a repeatable detector response are present at an evaporator joint.", operating:"Standing pressure is low and the compressor still operates; no evidence supports an electrical-only fault.", confirm:"A bubble test confirms the exact leaking joint.", diagnosis:"The sealed system is undercharged because the evaporator joint is leaking.", distractors:["The capillary is restricted even though the leak is confirmed","The thermostat is short cycling","The appliance needs refrigerant but no repair"], repair:"Recover the remaining charge, repair the joint, pressure-test with dry nitrogen, evacuate, and weigh in the factory charge.", repairDistractors:["Add refrigerant through the leak","Use oxygen for the pressure test","Vent the remaining charge because it is small"], explanation:"Confirm the leak, repair it, and restore the exact charge rather than repeatedly topping off." },
      { name:"Recovery connection", visual:"One access point is on the process stub while refrigerant may be trapped on the opposite side of a restriction.", operating:"Pressure equalization is slow and a single connection leaves a cold section holding refrigerant.", confirm:"A second approved access point can be installed after controlling the refrigerant.", diagnosis:"Improve access so refrigerant is not trapped during recovery.", distractors:["Increase cylinder pressure to force recovery","Stop when the first gauge reaches zero","Drill the tubing while pressurized"], repair:"Use appropriate high- and low-side access, recover to the required endpoint, then remove temporary fittings and seal the system.", repairDistractors:["Connect the vacuum pump directly to a full system","Vent the trapped side","Leave access valves uncapped"], explanation:"Restrictions and check devices can isolate refrigerant; recovery connections must address the complete circuit." },
      { name:"Small-appliance classification", visual:"The nameplate shows a factory-sealed appliance with a charge at or below five pounds.", operating:"The appliance is not an MVAC and was charged and hermetically sealed at the factory.", confirm:"The equipment fits the Section 608 small-appliance category.", diagnosis:"Treat the unit as a Type I small appliance and use the applicable recovery procedure.", distractors:["Any residential appliance is automatically Type II","Charge pressure alone determines certification type","Factory sealing eliminates recovery requirements"], repair:"Use Type I practices, certified recovery equipment, the correct endpoint, and documented disposal or service procedures.", repairDistractors:["Use MVAC equipment because the charge is small","Open the circuit before identification","Assume hydrocarbon refrigerants are harmless"], explanation:"Small-appliance classification depends on factory charge, hermetic sealing, and charge size—not merely where the unit is installed." }
    ],
    type2: [
      { name:"Confirmed refrigerant leak", visual:"Oil residue is present at a service valve and the condenser coil is clean.", operating:"With normal load and airflow, suction and head are low, superheat is high, and subcooling is low.", confirm:"Electronic detection and bubbles confirm the service-valve leak.", diagnosis:"The system is undercharged because the service valve is leaking.", distractors:["Restricted airflow is the primary fault","The system is overcharged","Noncondensables are raising head pressure"], repair:"Recover or isolate as appropriate, repair the valve, verify leak-free operation, evacuate, restore charge by approved method, and recommission.", repairDistractors:["Add refrigerant without repairing the leak","Vent to atmosphere before replacing the valve","Charge by suction pressure alone"], explanation:"The combined heat-transfer, pressure, superheat, subcooling, and leak-test evidence supports a confirmed leak and undercharge." },
      { name:"Condenser heat rejection", visual:"The condenser surface is matted with debris and discharge air recirculates into the intake.", operating:"Head pressure and subcooling are high while suction is near expected for the load.", confirm:"Head pressure falls after airflow is restored without removing refrigerant.", diagnosis:"Poor condenser heat rejection is causing the high head pressure.", distractors:["The system is necessarily overcharged","The evaporator has excessive airflow","The compressor has no load"], repair:"De-energize, clean the coil safely, correct recirculation or fan issues, then verify pressures and temperatures under stable load.", repairDistractors:["Recover charge until head pressure falls","Spray refrigerant on the condenser","Disable the high-pressure control"], explanation:"Correct heat-rejection problems before adjusting charge; operating data after cleaning confirms the diagnosis." },
      { name:"Low evaporator airflow", visual:"The filter and evaporator are loaded and blower airflow is below design.", operating:"Suction saturation is low and the coil begins to frost; superheat may not uniquely identify the root cause.", confirm:"Pressures and coil temperature normalize after airflow is restored.", diagnosis:"Restricted evaporator airflow is driving low suction and icing.", distractors:["Low suction proves refrigerant undercharge","The condenser is overfed","Noncondensables are present"], repair:"Correct filters, coil cleanliness, blower setup, and duct restrictions before evaluating charge under stable airflow.", repairDistractors:["Add refrigerant to raise suction pressure","Bypass the freeze protection","Increase head pressure by blocking the condenser"], explanation:"Airflow must be proven before using refrigerant readings to condemn the charge." },
      { name:"Liquid-line restriction", visual:"A temperature drop and flash gas appear across the liquid-line drier.", operating:"Suction is low, superheat is high, and refrigerant backs up in the condenser, producing normal-to-high subcooling.", confirm:"The drier outlet is colder than its inlet and the downstream liquid line is starved.", diagnosis:"A restricted liquid-line drier is starving the metering device.", distractors:["The system is simply undercharged","The compressor valves are leaking","The condenser fan is oversized"], repair:"Recover refrigerant, replace the restricted drier, inspect for contamination, evacuate, recharge, and verify the temperature drop is gone.", repairDistractors:["Add refrigerant until suction rises","Remove the drier and install straight tubing","Heat the drier while the system runs"], explanation:"High superheat with retained subcooling and a localized temperature drop distinguishes a restriction from undercharge." },
      { name:"Noncondensables", visual:"The condenser is clean and airflow is correct, but pressure remains higher than the refrigerant’s expected saturation pressure at ambient-equilibrated temperature.", operating:"Both head pressure and condenser split are abnormally high after charge quantity and airflow are verified.", confirm:"A standing pressure-temperature check after stabilization does not match the identified refrigerant.", diagnosis:"Air or other noncondensables are trapped in the refrigeration circuit.", distractors:["The evaporator filter is dirty","The system needs additional refrigerant","The crankcase heater is too warm"], repair:"Recover the charge, correct the evacuation or service procedure, evacuate with a micron gauge, and recharge with known refrigerant by weight.", repairDistractors:["Purge vapor from the condenser to atmosphere","Bleed the high side until pressure matches","Add oil to absorb the air"], explanation:"Noncondensables cannot be corrected by intentional purging; recover, evacuate, and recharge properly." },
      { name:"Overcharge", visual:"Condenser airflow is normal and no liquid-line restriction is found.", operating:"Head pressure and subcooling are high, superheat is low, and the weighed service history shows excess refrigerant was added.", confirm:"Calculated charge correction matches the manufacturer charging data.", diagnosis:"The system is overcharged.", distractors:["The system is undercharged","Low indoor airflow is the only possible cause","The compressor is rotating backward"], repair:"Recover excess refrigerant into an approved cylinder and verify final charge using manufacturer procedures under stable load.", repairDistractors:["Vent vapor until head pressure falls","Remove refrigerant without a scale or charging target","Block condenser airflow to hold pressure"], explanation:"Normal airflow plus high subcooling and documented excess charge supports overcharge." },
      { name:"Compressor burnout cleanup", visual:"Oil is acidic and dark after an electrical compressor failure.", operating:"Contamination is distributed through the circuit and a replacement compressor alone would be at risk.", confirm:"Acid-test results and inspection support a burnout cleanup procedure.", diagnosis:"The system requires contamination cleanup in addition to compressor replacement.", distractors:["Only the run capacitor needs replacement","Add new oil without removing contaminated refrigerant","Flush the system with oxygen"], repair:"Recover refrigerant, replace failed and contaminated components, install appropriate driers, evacuate, recharge, and monitor cleanup indicators.", repairDistractors:["Vent the contaminated charge","Reuse the old drier","Mix recovered refrigerant into clean stock"], explanation:"A burnout can leave acids and debris throughout the system; cleanup protects the replacement compressor." },
      { name:"Moisture contamination", visual:"A sight-glass indicator and operating symptoms suggest moisture after the circuit was left open.", operating:"Intermittent restriction changes as the metering-device area warms and cools.", confirm:"Service history and drier condition support moisture contamination.", diagnosis:"Moisture is freezing at the metering device and intermittently restricting flow.", distractors:["The system has a fixed overcharge","Condenser airflow is excessive","The compressor is necessarily undersized"], repair:"Recover refrigerant, replace the drier, minimize open time, evacuate deeply with a micron gauge, and verify dehydration before charging.", repairDistractors:["Purge with refrigerant repeatedly","Add alcohol without manufacturer approval","Heat the metering device and return the unit to service"], explanation:"A changing restriction near the metering device after moisture exposure points to inadequate dehydration." },
      { name:"Efficient recovery", visual:"A large charge and receiver permit liquid recovery before vapor recovery.", operating:"Long, small hoses and cold cylinders are slowing transfer.", confirm:"Short large-diameter hoses, correct valve positions, and a compatible recovery machine are available.", diagnosis:"Recover liquid first, then vapor, while controlling cylinder fill and temperature.", distractors:["Recover vapor only regardless of system design","Heat the recovery cylinder with an open flame","Use the vacuum pump as a recovery machine"], repair:"Use certified equipment, remove liquid efficiently, complete vapor recovery to the required level, and weigh and label the cylinder.", repairDistractors:["Mix refrigerants in one cylinder","Bypass the scale","Stop when system and cylinder pressures first equalize"], explanation:"Liquid-first recovery and lower flow resistance can shorten recovery without sacrificing safety or the required endpoint." },
      { name:"Leak-rule assessment", visual:"Service records show repeated additions on an appliance with a substantial full charge.", operating:"Rule applicability depends on refrigerant, full charge, appliance category, calculated leak rate, and the current regulatory program.", confirm:"The owner can provide charge calculations and prior service records for a defensible leak-rate assessment.", diagnosis:"Determine the applicable rule and leak rate before setting repair, verification, and recordkeeping obligations.", distractors:["Every leak has the same federal deadline","Only suction pressure determines the leak rate","Adding refrigerant erases the prior leak history"], repair:"Document the full charge and additions, repair confirmed leaks, complete applicable verification testing, and retain required records.", repairDistractors:["Top off without recording the quantity","Wait until the system is empty","Use the equipment age as the only compliance test"], explanation:"Large-appliance leak duties are fact-specific and must be evaluated under the current rule rather than memorized as one universal threshold." }
    ],
    type3: [
      { name:"Air and moisture ingress", visual:"Purge-unit runtime has increased and the chiller operates below atmospheric pressure.", operating:"Noncondensables accumulate at the condenser and raise pressure and energy use.", confirm:"Leak testing identifies an air leak on the vacuum side of the machine.", diagnosis:"A vacuum-side leak is admitting air and moisture, increasing purge operation.", distractors:["The chiller is overcharged solely because purge runtime increased","The evaporator water flow is too high","The rupture disk is designed to draw air inward"], repair:"Locate and repair the leak, service the purge unit, remove noncondensables, and verify improved purge runtime and efficiency.", repairDistractors:["Disable the purge unit","Vent refrigerant with the purge air","Pressurize the chiller with oxygen"], explanation:"Low-pressure appliances can draw air and moisture inward; the purge symptom should lead to leak repair, not routine venting." },
      { name:"Water-side tube leak", visual:"Refrigerant-side moisture is rising and water chemistry appears in the machine.", operating:"A leaking tube can introduce water into the refrigerant side while the chiller is under vacuum.", confirm:"Tube testing isolates a leaking evaporator tube.", diagnosis:"An evaporator tube leak is introducing water into the refrigerant side.", distractors:["The purge unit creates water as a normal byproduct","The compressor heater is boiling water into the system","The condenser is short of refrigerant"], repair:"Isolate and repair or plug the tube according to manufacturer limits, remove moisture, replace affected driers, evacuate, and verify water-side integrity.", repairDistractors:["Add refrigerant to push water back into the tube","Use oxygen for the pressure test","Ignore the leak if purge runtime is acceptable"], explanation:"Water contamination in a low-pressure machine can result from tube leakage and requires water-side and refrigerant-side correction." },
      { name:"Controlled leak-test pressure", visual:"The chiller must be brought to positive pressure for leak testing and its relief protection is intact.", operating:"Excessive test pressure could rupture the disk or damage the low-pressure shell.", confirm:"Dry nitrogen, a regulator, relief protection, and the manufacturer’s maximum test pressure are available.", diagnosis:"Use controlled dry nitrogen and stay within the manufacturer’s low-pressure test limit.", distractors:["Use oxygen because it is easy to detect","Pressurize until the rupture disk lifts","Use liquid refrigerant as the pressure source and vent afterward"], repair:"Warm or pressurize only as permitted, regulate nitrogen carefully, leak-test, recover any refrigerant mixture, and restore the machine safely.", repairDistractors:["Bypass the relief device","Hammer the shell while pressurized","Leave nitrogen in the chiller during charging"], explanation:"Low-pressure shells and rupture disks require tightly controlled test pressure and appropriate inert gas." },
      { name:"Required evacuation level", visual:"The low-pressure appliance is being opened for major service or prepared for disposal.", operating:"The recovery machine is capable of measuring absolute pressure at the required deep-vacuum endpoint.", confirm:"A calibrated absolute-pressure instrument can verify 25 mm Hg absolute.", diagnosis:"Recover the low-pressure appliance to 25 mm Hg absolute when the evacuation requirement applies.", distractors:["Stop at 25 inches Hg vacuum","Stop at 0 psig","Evacuate to 4 inches Hg vacuum because every appliance uses the same endpoint"], repair:"Use certified recovery equipment, verify 25 mm Hg absolute with the proper instrument, isolate, and document the recovery.", repairDistractors:["Use only a compound gauge estimate","Vent after reaching atmospheric pressure","Measure cylinder vacuum instead of appliance pressure"], explanation:"The low-pressure evacuation level is expressed as absolute pressure: 25 mm Hg absolute." },
      { name:"Refrigerant in oil", visual:"A large oil charge is scheduled for removal and dissolved refrigerant remains in the oil.", operating:"Warming and pressure reduction release refrigerant from the oil; opening too early would release it.", confirm:"The isolated section can be brought to no greater than 5 psig and connected to recovery.", diagnosis:"Recover refrigerant from the oil before draining it.", distractors:["Oil contains no meaningful refrigerant","Drain at operating pressure into an open pail","Add water to separate refrigerant from oil"], repair:"Reduce the appliance or isolated section to no greater than 5 psig, recover released refrigerant, drain into a controlled receiver, and handle oil properly.", repairDistractors:["Vent the oil container outdoors","Heat oil with an open flame","Dispose of oil in the refrigerant cylinder"], explanation:"Refrigerant dissolves in oil; pressure reduction and controlled handling are part of recovery." },
      { name:"Purge-unit refrigerant return", visual:"The purge unit separates noncondensables from refrigerant vapor.", operating:"Recovered refrigerant from the purge unit must return to the chiller rather than be discarded with purge air.", confirm:"The purge return is routed through the intended connection to the evaporator side.", diagnosis:"Return separated refrigerant from the purge unit to the evaporator through the designed path.", distractors:["Send all purge discharge to the recovery cylinder","Return liquid directly to the compressor suction","Vent the refrigerant fraction with the air"], repair:"Service the purge unit, verify separation and refrigerant return, repair air leaks, and monitor purge runtime.", repairDistractors:["Block the refrigerant return line","Run the purge continuously without diagnosis","Bypass the expansion device"], explanation:"A properly operating purge minimizes refrigerant loss while removing air and moisture from a low-pressure chiller." },
      { name:"Hydrostatic pressure protection", visual:"A liquid-full isolated section could warm while blocked between valves.", operating:"Thermal expansion of trapped liquid can create extreme hydrostatic pressure even without compressor operation.", confirm:"Relief devices and valve positions can protect the isolated section during service.", diagnosis:"Do not trap liquid without pressure relief; thermal expansion can rupture components.", distractors:["Liquid pressure cannot rise when the compressor is off","Closing every valve is always the safest isolation","The rupture disk protects every isolated hose and pipe"], repair:"Plan isolation with relief protection, avoid liquid-full trapped sections, and control temperature during recovery and service.", repairDistractors:["Heat trapped liquid to speed recovery","Cap both ends of a liquid-full hose","Rely on hose stretch as pressure relief"], explanation:"Hydrostatic pressure is a major hazard whenever liquid is isolated and allowed to warm." },
      { name:"Safe liquid charging", visual:"A low-pressure chiller is ready for charging after evacuation and leak verification.", operating:"Introducing liquid into a deep vacuum too quickly can freeze water in tubes or create damaging thermal stress.", confirm:"The manufacturer charging connection and controlled procedure are available.", diagnosis:"Charge through the specified connection at a controlled rate, protecting the evaporator and compressor.", distractors:["Pour liquid refrigerant into the purge line","Start the compressor in a deep vacuum","Add liquid as fast as the hose allows"], repair:"Follow the manufacturer sequence, establish the required water conditions, break vacuum safely, meter charge, and verify operating level.", repairDistractors:["Bypass low-pressure safeties","Use the rupture disk connection for charging","Charge by shell temperature alone"], explanation:"Low-pressure charging requires control of thermal stress, water conditions, and compressor protection." },
      { name:"Vacuum-side leak detection", visual:"The machine is below atmospheric pressure, so an operating leak draws air inward rather than pushing refrigerant out.", operating:"Conventional bubble testing may not reveal an inward leak while the chiller is under vacuum.", confirm:"Purge trends, tracer methods, or controlled positive-pressure testing can localize the leak safely.", diagnosis:"Use a method suited to inward leakage on a low-pressure appliance.", distractors:["Look only for outward oil bubbles while the machine is under vacuum","Add refrigerant until the leak blows outward","Disable the purge to make the leak easier to hear"], repair:"Use approved tracer or controlled-pressure methods, repair the leak, evacuate, and verify reduced air ingress.", repairDistractors:["Pressurize with oxygen","Exceed the rupture-disk rating","Accept continuous purge operation as the repair"], explanation:"Leak direction changes below atmospheric pressure, so test strategy must change as well." },
      { name:"Low-pressure recovery rate", visual:"Recovery slows as refrigerant temperature and pressure fall.", operating:"Cold water and cold refrigerant reduce vapor pressure, while excessive heating could damage the machine.", confirm:"Water temperature can be managed within manufacturer limits and liquid can be removed before vapor recovery.", diagnosis:"Use safe temperature management and liquid-first recovery to maintain the recovery rate.", distractors:["Apply a torch to the chiller shell","Inject air to raise pressure","Stop recovery at 0 psig"], repair:"Remove liquid first where possible, maintain permitted water temperature, use appropriate hoses and equipment, and continue to the required absolute pressure.", repairDistractors:["Heat the recovery cylinder above its rating","Bypass low-temperature protections without monitoring","Vent vapor when recovery slows"], explanation:"Low-pressure recovery becomes slower as saturation pressure falls; safe heat and flow management improve performance." }
    ]
  };

  const CONTEXTS = {
    core: [
      ["The Unopened Circuit","Baker Residence","split heat pump","R-410A","8.2 lb","A compressor replacement is scheduled after a grounded winding was confirmed."],
      ["The Retrofit Estimate","Maple Street Office","packaged rooftop unit","R-22","18 lb","The owner is comparing repair, retrofit, and replacement options."],
      ["The Crowded Cylinder","Northside Market","walk-in freezer","R-404A","24 lb","Recovery must begin before a leaking receiver valve is replaced."],
      ["The Transfer Question","City Library","air-cooled chiller","R-407C","42 lb","Recovered refrigerant may be transferred to a different owner."],
      ["The Blend on the Scale","Willow Apartments","ductless heat pump","R-410A","5.6 lb","A repaired circuit needs an accurate final charge."],
      ["The Wet System","Lakeside Café","reach-in freezer","R-448A","3.8 lb","The circuit was left open after a delayed compressor delivery."],
      ["The Basement Call","Pine Medical Suite","split air conditioner","R-32","7.4 lb","Service must be planned in a tight mechanical closet."],
      ["The Refrigerant Choice","Oak School","rooftop unit","R-454B","13 lb","A replacement refrigerant and equipment plan needs review."],
      ["The Unlabeled Machine","Riverside Hotel","heat pump","R-410A","31 lb","Two recovery machines are on site but only one has a certification label."],
      ["The Missing Log","Harbor Grocery","refrigeration rack","R-22","620 lb","Repeated refrigerant additions have not been reconciled."],
      ["The Service Valve","Cedar Townhomes","split air conditioner","R-410A","9.1 lb","A service valve must be replaced without releasing the system charge."],
      ["The Old Receiver","Summit Restaurant","walk-in cooler","R-404A","36 lb","The only available recovery cylinder may not have enough remaining capacity."],
      ["The Credential Check","County Annex","packaged heat pump","R-407C","22 lb","Dispatch assigned a technician with a limited certification."],
      ["The Clean Refrigerant","Greenfield Lab","process cooler","R-134a","48 lb","The owner wants recovered refrigerant sold to another business."],
      ["The Fractionated Charge","Parkside Condos","multi-zone system","R-410A","12.5 lb","A partially used blend cylinder is being prepared for charging."],
      ["The Open Drum","West End Bakery","condensing unit","R-448A","11 lb","Oil and drier replacement followed a long period open to humid air."],
      ["The Confined Plant","Metro Archive","computer-room unit","R-410A","16 lb","A refrigerant leak alarmed in a small equipment room."],
      ["The Substitute Proposal","Hillcrest Church","older rooftop unit","R-22","15 lb","A salesperson called a new refrigerant a universal drop-in."],
      ["The Backup Recoverer","Elm Community Center","split system","R-410A","10 lb","The primary recovery machine failed before opening the circuit."],
      ["The Repeat Top-Off","Central Foods","refrigeration rack","R-22","540 lb","Service tickets show frequent additions but no calculated leak rate."]
    ],
    type1: [
      ["The Warm Refrigerator","Alvarez Residence","household refrigerator","R-134a","5.0 oz","The fresh-food section warms even though the compressor runs."],
      ["The Silent Freezer","Baker Residence","upright freezer","R-600a","2.1 oz","The compressor will not start and food is thawing."],
      ["The Dorm Fridge","North Hall","compact refrigerator","R-134a","2.8 oz","The appliance is scheduled for a sealed-system repair."],
      ["The Leaking Tap","Corner Café","countertop cooler","R-290","3.2 oz","A temporary service valve was left on a previous repair."],
      ["The Scrap Row","City Recycling","mixed household refrigerators","mixed","varies","Several appliances are ready for final disposal."],
      ["The Frosted Capillary","Maple Apartments","window air conditioner","R-32","14 oz","Cooling fades as frost develops at one point in the liquid path."],
      ["The Exact Charge","Dental Office","water cooler","R-134a","6.5 oz","A repaired system needs its factory blend charge restored."],
      ["The Oily Joint","Riverside Motel","PTAC under 5 lb factory charge","R-410A","42 oz","Oil staining is visible at an evaporator return bend."],
      ["The Trapped Charge","School Kitchen","ice maker","R-404A","28 oz","Recovery stalls with refrigerant trapped beyond a restriction."],
      ["The Five-Pound Line","Vending Depot","beverage merchandiser","R-290","5.3 oz","The team must confirm the correct certification category."],
      ["The Running Dehumidifier","Archive Room","portable dehumidifier","R-134a","7 oz","The fan runs and the compressor operates, but little water is removed."],
      ["The Locked Compressor","Lake Cabin","chest freezer","R-600a","1.9 oz","The compressor is mechanically seized before disposal."],
      ["The Passive Recovery Bag","Appliance Lab","compact freezer","R-134a","3 oz","A system-dependent recovery demonstration is scheduled."],
      ["The Saddle Valve","Corner Market","small display cooler","R-290","4.1 oz","A piercing valve is seeping after a prior service call."],
      ["The Disposal Tag","University Housing","window air conditioner","R-410A","36 oz","Facilities needs proof of recovery before recycling."],
      ["The Intermittent Ice","Break Room","countertop ice maker","R-134a","4.8 oz","Cooling returns briefly when the capillary area warms."],
      ["The Zeotropic Charge","Hotel Lobby","water dispenser","R-407C","18 oz","The sealed system was repaired and evacuated."],
      ["The Evaporator Leak","Clinic Lab","under-counter refrigerator","R-134a","5.5 oz","A detector responds at an evaporator joint."],
      ["The Check Valve","Food Truck","small ice machine","R-290","3.0 oz","A restriction makes one recovery connection ineffective."],
      ["The Factory-Sealed Unit","Maintenance Shop","portable air conditioner","R-32","24 oz","The work order was assigned as a general residential call."]
    ],
    type2: [
      ["The House That Won't Cool","Alvarez Residence","four-ton split system","R-410A","12 lb","The system runs continuously but the home stays warm."],
      ["The Hot Rooftop","Baker Pharmacy","packaged rooftop unit","R-410A","18 lb","Head pressure trips occur every hot afternoon."],
      ["The Frozen Coil","Northside Office","split heat pump","R-410A","9 lb","Ice forms on the evaporator after an hour of cooling."],
      ["The Starved Walk-In","Corner Market","walk-in freezer","R-404A","32 lb","Box temperature rises while the compressor runs continuously."],
      ["The High Standing Pressure","City Library","air-cooled chiller","R-407C","48 lb","Pressure remains unexpectedly high after shutdown and stabilization."],
      ["The Heavy Charge","Maple Apartments","packaged heat pump","R-410A","21 lb","Performance worsened after refrigerant was added yesterday."],
      ["The Burned Compressor","Riverside Restaurant","walk-in condensing unit","R-404A","26 lb","A grounded compressor has left dark acidic oil."],
      ["The Intermittent Restriction","Summit School","rooftop unit","R-410A","15 lb","Suction falls unpredictably after a recent coil replacement."],
      ["The Slow Recovery","Harbor Grocery","medium-temperature rack","R-448A","180 lb","A receiver replacement requires efficient recovery of a large charge."],
      ["The Repeated Additions","Central Foods","refrigeration rack","R-22","520 lb","Service records show a rising pattern of top-offs."],
      ["The Leaking Core","Cedar Townhomes","three-ton split system","R-410A","8 lb","Cooling has declined gradually over two weeks."],
      ["The Cottonwood Coil","Westside Bank","rooftop unit","R-410A","17 lb","The unit trips high pressure during peak outdoor load."],
      ["The Closed Damper","County Annex","variable-air-volume air handler","R-410A","38 lb","Several zones are warm and the suction line frosts."],
      ["The Cold Drier","Lakeside Deli","walk-in cooler","R-404A","29 lb","A sharp temperature drop appears in the liquid line."],
      ["The Poor Evacuation","Metro Data Room","computer-room unit","R-407C","44 lb","Head pressure stayed high after a major repair and recharge."],
      ["The Extra Cylinder","Oak Medical Center","split system","R-410A","14 lb","A full recovery cylinder was mistakenly weighed into the system."],
      ["The Acid Test","Greenfield Lab","process chiller","R-134a","76 lb","A replacement compressor is ready after an electrical burnout."],
      ["The Wet Drier","Pine Hotel","heat-pump rooftop unit","R-410A","23 lb","The system was open during a rain delay."],
      ["The Receiver Job","Union Warehouse","condensing unit","R-448A","95 lb","The receiver must be changed before the next production shift."],
      ["The Compliance Review","Regional Arena","comfort-cooling chiller","R-22","310 lb","The owner needs a leak-rate and repair-plan review."]
    ],
    type3: [
      ["The Busy Purge Unit","City Hall","centrifugal chiller","R-123","1,100 lb","Purge runtime has doubled and efficiency is falling."],
      ["The Wet Evaporator","Memorial Hospital","low-pressure chiller","R-1233zd(E)","1,250 lb","Moisture indicators rise after a condenser-water event."],
      ["The Rupture-Disk Test","Central Library","centrifugal chiller","R-123","900 lb","The machine must be leak-tested after seasonal shutdown."],
      ["The Disposal Vacuum","Old Mill","retired low-pressure chiller","R-11","1,400 lb","The appliance is being prepared for dismantling."],
      ["The Oil Change","University Plant","centrifugal chiller","R-123","1,050 lb","A major oil service is scheduled during shutdown."],
      ["The Purge Return","Riverfront Hotel","low-pressure chiller","R-123","780 lb","Refrigerant loss is suspected at the purge unit."],
      ["The Trapped Liquid","County Courthouse","centrifugal chiller","R-1233zd(E)","1,300 lb","An isolated liquid line will warm during a valve replacement."],
      ["The First Charge","Research Center","new low-pressure chiller","R-1233zd(E)","1,500 lb","The evacuated machine is ready for initial charging."],
      ["The Inward Leak","Museum Archive","centrifugal chiller","R-123","820 lb","Air enters the machine but no outward bubbles are visible."],
      ["The Cold Recovery","North Campus","low-pressure chiller","R-11","1,200 lb","Recovery has slowed sharply as water and refrigerant cool."],
      ["The Overnight Purge","Convention Center","centrifugal chiller","R-123","1,450 lb","Purge operation continues long after the load falls."],
      ["The Tube Sheet","Aquatic Center","low-pressure chiller","R-1233zd(E)","980 lb","Water contamination appears after a tube-cleaning project."],
      ["The Positive-Pressure Test","State Archive","centrifugal chiller","R-123","870 lb","A vacuum-side flange must be checked for leakage."],
      ["The Absolute Reading","Factory Office","retired low-pressure chiller","R-11","760 lb","The recovery crew is unsure whether the endpoint is absolute or gauge pressure."],
      ["The Refrigerant-Rich Oil","Airport Plant","centrifugal chiller","R-123","1,600 lb","Oil foams during preparation for draining."],
      ["The Purge Separator","Coastal Hotel","low-pressure chiller","R-123","940 lb","The purge discharge appears to carry excess refrigerant."],
      ["The Blocked-In Line","Civic Center","centrifugal chiller","R-1233zd(E)","1,180 lb","Liquid may be trapped between two closed service valves."],
      ["The Thermal Shock Risk","Medical Campus","low-pressure chiller","R-1233zd(E)","1,350 lb","Charging is planned immediately after deep evacuation."],
      ["The Helium Trace","Records Center","centrifugal chiller","R-123","830 lb","The crew must locate an inward leak without overpressurizing the shell."],
      ["The Slow Final Inches","Industrial Plant","low-pressure chiller","R-11","1,700 lb","Vapor recovery is slow near the required endpoint."]
    ]
  };

  function scenario(group, context, index) {
    const [title, site, equipment, refrigerant, charge, complaint] = context;
    const focus = FOCUS[group][index % FOCUS[group].length];
    return {
      id: `${group}-${String(index + 1).padStart(2, "0")}`,
      number: index + 1,
      group,
      title,
      site,
      equipment,
      refrigerant,
      charge,
      complaint,
      focus,
      customer: group === "type3" ? "Plant operator" : group === "core" ? "Site contact" : "Equipment owner",
      quote: complaint,
      avatar: group === "type3" ? "🧑🏽‍🔧" : group === "type2" ? "🧑🏾" : group === "type1" ? "🧑🏻" : "🧑🏼‍💼",
      tags: [GROUPS[group].name, equipment, refrigerant, `${charge} charge`]
    };
  }

  const SCENARIOS = Object.fromEntries(Object.entries(CONTEXTS).map(([group, contexts]) => [group, contexts.map((context, index) => scenario(group, context, index))]));

  window.COOL_CALL_CURRICULUM = {
    groups: GROUPS,
    scenarios: SCENARIOS,
    verifiedOn: "2026-07-16",
    sources: [
      "https://www.epa.gov/section608/section-608-technician-certification-requirements",
      "https://www.epa.gov/section608/stationary-refrigeration-service-practice-requirements",
      "https://www.epa.gov/section608/required-level-evacuation-appliances",
      "https://www.epa.gov/section608/stationary-refrigeration-leak-repair-requirements"
    ]
  };
})();
